services:
  app:
    build:
      context: ./
      args:
        - PROJECT_NAME=<project-name>
    container_name: "angular-<project-name>"
    cpu_count: 1
    mem_limit: 512m
    tty: true
    ports:
      - 4201:80
